//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALChamCong.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.timekeepingdetails = new HashSet<timekeepingdetails>();
        }
    
        public int ID { get; set; }
        public string TenNV { get; set; }
        public string Email { get; set; }
        public string Matkhau { get; set; }
        public Nullable<int> Tuoi { get; set; }
        public Nullable<int> SDT { get; set; }
        public Nullable<int> MaCV { get; set; }
        public Nullable<int> MaPB { get; set; }
        public Nullable<int> MaCT { get; set; }
        public Nullable<int> MaLuong { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Department Department { get; set; }
        public virtual Userole Userole { get; set; }
        public virtual salary salary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<timekeepingdetails> timekeepingdetails { get; set; }
    }
}
