//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALChamCong.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class timekeepingdetails
    {
        public int EmployeeID { get; set; }
        public int timekeepingID { get; set; }
        public Nullable<System.TimeSpan> checkin { get; set; }
        public Nullable<System.TimeSpan> checkout { get; set; }
        public Nullable<bool> dayoff { get; set; }
        public Nullable<int> overtime { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual timekeeping timekeeping { get; set; }
    }
}
